//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Hoa.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public string IDChiTietDonHang { get; set; }
        public int SoLuongHoa { get; set; }
        public int ThanhTien { get; set; }
        public System.DateTime NgayTao { get; set; }
        public string TenNguoiDung { get; set; }
        public Nullable<int> DienThoai { get; set; }
        public string DiaChi { get; set; }
        public Nullable<int> IDHoa { get; set; }
        public string IDDonHang { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Hoa Hoa { get; set; }
    }
}
